// Generated by gencpp from file nist_gear/AGVControlRequest.msg
// DO NOT EDIT!


#ifndef NIST_GEAR_MESSAGE_AGVCONTROLREQUEST_H
#define NIST_GEAR_MESSAGE_AGVCONTROLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nist_gear
{
template <class ContainerAllocator>
struct AGVControlRequest_
{
  typedef AGVControlRequest_<ContainerAllocator> Type;

  AGVControlRequest_()
    : shipment_type()  {
    }
  AGVControlRequest_(const ContainerAllocator& _alloc)
    : shipment_type(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _shipment_type_type;
  _shipment_type_type shipment_type;





  typedef boost::shared_ptr< ::nist_gear::AGVControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nist_gear::AGVControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AGVControlRequest_

typedef ::nist_gear::AGVControlRequest_<std::allocator<void> > AGVControlRequest;

typedef boost::shared_ptr< ::nist_gear::AGVControlRequest > AGVControlRequestPtr;
typedef boost::shared_ptr< ::nist_gear::AGVControlRequest const> AGVControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nist_gear::AGVControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nist_gear::AGVControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nist_gear

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'nist_gear': ['/home/gents/ariac2020/ws/src/ARIAC/nist_gear/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nist_gear::AGVControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nist_gear::AGVControlRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nist_gear::AGVControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nist_gear::AGVControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nist_gear::AGVControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nist_gear::AGVControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nist_gear::AGVControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3cb3e9e27775802f44b63ca135bf6dec";
  }

  static const char* value(const ::nist_gear::AGVControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3cb3e9e27775802fULL;
  static const uint64_t static_value2 = 0x44b63ca135bf6decULL;
};

template<class ContainerAllocator>
struct DataType< ::nist_gear::AGVControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nist_gear/AGVControlRequest";
  }

  static const char* value(const ::nist_gear::AGVControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nist_gear::AGVControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"\n"
"\n"
"\n"
"string shipment_type\n"
"\n"
;
  }

  static const char* value(const ::nist_gear::AGVControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nist_gear::AGVControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.shipment_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AGVControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nist_gear::AGVControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nist_gear::AGVControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "shipment_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.shipment_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIST_GEAR_MESSAGE_AGVCONTROLREQUEST_H
