// Generated by gencpp from file nist_gear/ConveyorBeltState.msg
// DO NOT EDIT!


#ifndef NIST_GEAR_MESSAGE_CONVEYORBELTSTATE_H
#define NIST_GEAR_MESSAGE_CONVEYORBELTSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nist_gear
{
template <class ContainerAllocator>
struct ConveyorBeltState_
{
  typedef ConveyorBeltState_<ContainerAllocator> Type;

  ConveyorBeltState_()
    : power(0.0)
    , enabled(false)  {
    }
  ConveyorBeltState_(const ContainerAllocator& _alloc)
    : power(0.0)
    , enabled(false)  {
  (void)_alloc;
    }



   typedef double _power_type;
  _power_type power;

   typedef uint8_t _enabled_type;
  _enabled_type enabled;





  typedef boost::shared_ptr< ::nist_gear::ConveyorBeltState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nist_gear::ConveyorBeltState_<ContainerAllocator> const> ConstPtr;

}; // struct ConveyorBeltState_

typedef ::nist_gear::ConveyorBeltState_<std::allocator<void> > ConveyorBeltState;

typedef boost::shared_ptr< ::nist_gear::ConveyorBeltState > ConveyorBeltStatePtr;
typedef boost::shared_ptr< ::nist_gear::ConveyorBeltState const> ConveyorBeltStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nist_gear::ConveyorBeltState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nist_gear::ConveyorBeltState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nist_gear

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'nist_gear': ['/home/gents/ariac2020/ws/src/ARIAC/nist_gear/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nist_gear::ConveyorBeltState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nist_gear::ConveyorBeltState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nist_gear::ConveyorBeltState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nist_gear::ConveyorBeltState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nist_gear::ConveyorBeltState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nist_gear::ConveyorBeltState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nist_gear::ConveyorBeltState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c0b232b8dd148cb7c71d4df1ea72012c";
  }

  static const char* value(const ::nist_gear::ConveyorBeltState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc0b232b8dd148cb7ULL;
  static const uint64_t static_value2 = 0xc71d4df1ea72012cULL;
};

template<class ContainerAllocator>
struct DataType< ::nist_gear::ConveyorBeltState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nist_gear/ConveyorBeltState";
  }

  static const char* value(const ::nist_gear::ConveyorBeltState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nist_gear::ConveyorBeltState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Conveyor belt state message\n"
"float64 power  # power of the belt (percentage, in +Y direction of belt frame)\n"
"bool enabled  # true if the power of the belt can be modified; false if the belt is stopped\n"
;
  }

  static const char* value(const ::nist_gear::ConveyorBeltState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nist_gear::ConveyorBeltState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.power);
      stream.next(m.enabled);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConveyorBeltState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nist_gear::ConveyorBeltState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nist_gear::ConveyorBeltState_<ContainerAllocator>& v)
  {
    s << indent << "power: ";
    Printer<double>::stream(s, indent + "  ", v.power);
    s << indent << "enabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enabled);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIST_GEAR_MESSAGE_CONVEYORBELTSTATE_H
